spring:
  application:
    name: greeting-service
greeting-service:
  greeting: "Prontinho"
  default-value: "Mondo"
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
